### PR TITLE
Open Source List Update

### PR DESCRIPTION
**Pull request by SkyTech6**
- Removed Outdated Mods, that's not good to learn from. 
- Added an assortment of the active mods
- Broke them up by developer for less clutter
- Moved frameworks to the bottom

### CODE REVIEW

**Comment by Odjit** [comment]
I think breaking it up by category would be more useful than by author. I do like the additions, but I do still find old mods to be useful for review. It'll take me some time to comb through this and tweak, leaving it up till I get some time over holiday hopefully.

**Comment by SkyTech6** [comment]
This was actually kinda awful to make. I used the Thunderstore API to grab all mods marked with 1.0 Update. That file was massive because it contains version history. I ran that through a script to filter out all but the newest version (because description is in there). And then I had AI build out the table to my HTML layout. 

This was a bad process and yea it did miss some; although it's not intended to be a full list. 

I think preferably it would contain a selection of mods that are _good_ examples of modding; don't contain too much information to overload the reader but enough to learn something? Or maybe a tag like "Easy to Learn From"? 

If we're not wanting to update this here now then I'll probably work on breaking this up into something more easily modified going forward.

**Comment by SkyTech6** [comment]
Yea I had their types included originally... but in my modification of the file I accidently deleted that field and just abandoned hope as my ChatGPT ran out of tokens for modifying the massive file. 

Also a slight thing that confused me doing this was chino's XPRising; I thought about messaging him while doing this. All three of the mods that make up the server, client, and framework seem to be in the same repo. 

But now that you mention it yea; I don't think this included Watermark or the other client mods. Just Eclipse and FOV.

**Comment by SkyTech6** [comment]
image

So something like this? 

I have it generating at build from the json file (modified to save space)

```csharp
<h1>Client Mods</h1>
{% assign client_mods = "CrimsonFOV,ClientUI,RemoveVersionWatermark,Eclipse" | split: "," | sort %}
<table>
  <tr>
    <th>Mod Name</th>
    <th>Description</th>
    <th>Author</th>
  </tr>
  {% for mod_name in client_mods %}
    {% assign mod = site.data.OpenSourceMods | where: "name", mod_name | first %}
    {% assign latest_version = mod.versions | first %}
    <tr>
      <td><a href="{{ latest_version.website_url }}">{{ mod.name }}</a></td>
      <td>{{ latest_version.description }}</td>
      <td><a href="https://github.com/{{ mod.owner }}">{{ mod.owner }}</a></td>
    </tr>
  {% endfor %}
</table>
```

**Comment by Odjit** [comment]
Also another note:

On the wiki edit page, we state that the wiki is in markdown. I understand that HTML may seem like a more powerful tool, but the wiki is designed to be easy for everyone to use, regardless of their technical expertise. Markdown is simpler, quicker, and keeps our focus on content rather than formatting. It’s a lot easier to read and maintain. If there’s a specific formatting need, we can always incorporate HTML elements within Markdown where needed, but sticking to Markdown for the bulk of the content ensures that the wiki stays efficient and accessible for everyone.

I noticed that you’ve made this page's content dynamically load. The issue with this approach is that dynamic content doesn't render properly in the preview mode, which makes it difficult for others to review or edit the page before it’s published.

**Comment by SkyTech6** [comment]
Ah I use a live site instead of preview mode; prefer having matching test to production environment. 

https://vrising.wiki/dev/open%20source.html

You can see the change there. 

In this instance Markdown is definitely not quicker as it would include probably well over an hour of copy pasting and the page would be absolutely massive in length. It would be quite honestly a mess. Not to mention maintaining the page this way becomes automation instead of relying on people to manually edit it. 

Simply pull the json file from Thunderstore's API and then replace the file here. 

This wouldn't be the only page in the wiki to use html to save on tedious markdown as the Prefabs page does almost the same thing.

**Comment by Odjit** [comment]
Prefabs does it because it is far more massive amounts of data that also don't require curating.

I do see the use of it here, but I'm on the fence because I think the examples of code should be more curated/smaller lists. It at the very least will need a little note about how to update it for future editors. Maybe add the info to the "editing the wiki" page? Or it waits for the new discord channel for wiki additions from those uncomfortable with Github. Similarly I need to do that for the prefabs page, because that is def going to need updating come 1.1. 


I've also been pondering on the idea of more categories than just server/client/framework. Some things like Gameplay Enhancements (like KindredArenas), User Interface (like the RPG client mods), Performance Optimizations (we don't have any but its common in other games so maybe one day? lol), Server Management ( crimson chat, bans, KC), Content Mods (XP Rising, Bloodcraft, LeadAHorseToWater etc.), and Utility and Frameworks (CSQL, VCF, KindredExtract). I know some mods will overlap in some areas for code examples though. Any thoughts on venturing outside the triumvate?

**Pull request merged**
